import Header from "@/components/Header/Header";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId="399902958239-82hndr809hb3s2v59qo5ti0mgl849iun.apps.googleusercontent.com">
        <body>
          <Header />
          <div>{children}</div>
        </body>
      </GoogleOAuthProvider>
    </html>
  );
}
